fix indent for editorconfig

diff --git a/docs/deps/gh-md-toc b/docs/deps/gh-md-toc
--- a/docs/deps/gh-md-toc
+++ b/docs/deps/gh-md-toc
@@ -70,9 +70,9 @@ gh_toc_md2html() {
     local gh_tmp_file_md=$gh_file_md
     if [ "$skip_header" = "yes" ]; then
         if grep -Fxq "<!--te-->" "$gh_src"; then
-          # cut everything before the toc
-          gh_tmp_file_md=$gh_file_md~~
-          sed '1,/<!--te-->/d' $gh_file_md > $gh_tmp_file_md
+            # cut everything before the toc
+            gh_tmp_file_md=$gh_file_md~~
+            sed '1,/<!--te-->/d' $gh_file_md > $gh_tmp_file_md
         fi
     fi
 
@@ -154,16 +154,16 @@ gh_toc(){
     else
         local rawhtml=$(gh_toc_md2html "$gh_src" "$skip_header")
         if [ "$rawhtml" == "XXNetworkErrorXX" ]; then
-             echo "Parsing local markdown file requires access to github API"
-             echo "Please make sure curl is installed and check your network connectivity"
-             exit 1
+            echo "Parsing local markdown file requires access to github API"
+            echo "Please make sure curl is installed and check your network connectivity"
+            exit 1
         fi
         if [ "$rawhtml" == "XXRateLimitXX" ]; then
-             echo "Parsing local markdown file requires access to github API"
-             echo "Error: You exceeded the hourly limit. See: https://developer.github.com/v3/#rate-limiting"
-             TOKEN_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/token.txt"
-             echo "or place GitHub auth token here: ${TOKEN_FILE}"
-             exit 1
+            echo "Parsing local markdown file requires access to github API"
+            echo "Error: You exceeded the hourly limit. See: https://developer.github.com/v3/#rate-limiting"
+            TOKEN_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/token.txt"
+            echo "or place GitHub auth token here: ${TOKEN_FILE}"
+            exit 1
         fi
         local toc=`echo "$rawhtml" | gh_toc_grab "$gh_src_copy" "$indent"`
         echo "$toc"
@@ -221,21 +221,21 @@ gh_toc_grab() {
 
     href_regex="/href=\"[^\"]+?\"/"
     common_awk_script='
-                     modified_href = ""
-                     split(href, chars, "")
-                     for (i=1;i <= length(href); i++) {
-                         c = chars[i]
-                         res = ""
-                         if (c == "+") {
-                             res = " "
-                         } else {
-                             if (c == "%") {
-                                 res = "\\x"
-                             } else {
-                                 res = c ""
-                             }
-                         }
-                         modified_href = modified_href res
+                    modified_href = ""
+                    split(href, chars, "")
+                    for (i=1;i <= length(href); i++) {
+                        c = chars[i]
+                        res = ""
+                        if (c == "+") {
+                            res = " "
+                        } else {
+                            if (c == "%") {
+                                res = "\\x"
+                            } else {
+                                res = c ""
+                            }
+                        }
+                        modified_href = modified_href res
                     }
                     print sprintf("%*s", (level-1)*'"$2"', "") "* [" text "](" gh_url  modified_href ")"
                     '
@@ -243,19 +243,19 @@ gh_toc_grab() {
         grepcmd="pcregrep -o"
         echoargs=""
         awkscript='{
-                     level = substr($0, 3, 1)
-                     text = substr($0, match($0, /<\/span><\/a>[^<]*<\/h/)+11, RLENGTH-14)
-                     href = substr($0, match($0, '$href_regex')+6, RLENGTH-7)
-                     '"$common_awk_script"'
+                    level = substr($0, 3, 1)
+                    text = substr($0, match($0, /<\/span><\/a>[^<]*<\/h/)+11, RLENGTH-14)
+                    href = substr($0, match($0, '$href_regex')+6, RLENGTH-7)
+                    '"$common_awk_script"'
                 }'
     else
         grepcmd="grep -Eo"
         echoargs="-e"
         awkscript='{
-                     level = substr($0, 3, 1)
-                     text = substr($0, match($0, /<\/span><\/a>.*<\/h/)+11, RLENGTH-14)
-                     href = substr($0, match($0, '$href_regex')+6, RLENGTH-7)
-                     '"$common_awk_script"'
+                    level = substr($0, 3, 1)
+                    text = substr($0, match($0, /<\/span><\/a>.*<\/h/)+11, RLENGTH-14)
+                    href = substr($0, match($0, '$href_regex')+6, RLENGTH-7)
+                    '"$common_awk_script"'
                 }'
     fi
 
